version: '3'
services:
  node0:
    image: primihub/primihub-node:2022-10-08-18-02-28
    restart: "always"
    container_name: node0_primihub
    ports:
      - "8050:50050"
      - "10120:12120"
      - "10121:12121"
    volumes:
      - ./config:/app/config
      - ./data:/data
    entrypoint:
      - "/bin/bash"
      - "-c"
      - "./primihub-node --service_port=50050  --node_id=node0 --config=/app/config/primihub_node0.yaml"
    networks:
      testing_net:
        ipv4_address: 172.28.1.10
    depends_on:
      - simple_bootstrap_node

  node1:
    image: primihub/primihub-node:2022-10-08-18-02-28
    restart: "always"
    container_name: node1_primihub
    ports:
      - "8051:50051"
      - "11120:12120"
      - "11121:12121"
    volumes:
      - ./config:/app/config
      - ./data:/data
    entrypoint:
      - "/bin/bash"
      - "-c"
      - "./primihub-node --service_port=50051 --node_id=node1 --config=/app/config/primihub_node1.yaml"
    networks:
      testing_net:
        ipv4_address: 172.28.1.11
    depends_on:
      - simple_bootstrap_node

  node2:
    image: primihub/primihub-node:2022-10-08-18-02-28
    restart: "always"
    container_name: node2_primihub
    ports:
      - "8052:50052"
      - "12120:12120"
      - "12121:12121"
    volumes:
      - ./config:/app/config
      - ./data:/data
    entrypoint:
      - "/bin/bash"
      - "-c"
      - "./primihub-node --service_port=50052 --node_id=node2 --config=/app/config/primihub_node2.yaml"
    networks:
      testing_net:
        ipv4_address: 172.28.1.12
    depends_on:
      - simple_bootstrap_node

  redis:
    image: redis:latest 
    container_name: redis_meta_service 
    restart: "always"
    ports:
      - "6379:6379"
    volumes:
      - ./config/redis.conf:/etc/redis/redis.conf
      - ./data:/data
    command: redis-server /etc/redis/redis.conf
    networks:
      testing_net:
        ipv4_address: 172.28.1.13

networks:
  testing_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16
